/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import koneksiDB.Koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author amwulandesign
 */
public class FrmMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuUtama
     */
    public FrmMenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dpMenuUtama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuStaff = new javax.swing.JMenu();
        menuSpp = new javax.swing.JMenu();
        menuSiswa = new javax.swing.JMenu();
        menuTransaksi = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        rptBiayaSpp = new javax.swing.JMenuItem();
        rptDataSiswa = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(70, 173, 169));
        jPanel1.setLayout(null);

        javax.swing.GroupLayout dpMenuUtamaLayout = new javax.swing.GroupLayout(dpMenuUtama);
        dpMenuUtama.setLayout(dpMenuUtamaLayout);
        dpMenuUtamaLayout.setHorizontalGroup(
            dpMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        dpMenuUtamaLayout.setVerticalGroup(
            dpMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(dpMenuUtama);
        dpMenuUtama.setBounds(60, 140, 900, 500);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainMenu.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 730);

        jMenu1.setText("FILE");

        jMenuItem1.setText("LOGOUT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        menuStaff.setText("STAFF");
        menuStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuStaffMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuStaff);

        menuSpp.setText("SPP");
        menuSpp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSppMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSpp);

        menuSiswa.setText("DATA SISWA");
        menuSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSiswaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSiswa);

        menuTransaksi.setText("TRANSAKSI");
        menuTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTransaksiMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuTransaksi);

        jMenu2.setText("LAPORAN");

        rptBiayaSpp.setText("BIAYA SPP");
        rptBiayaSpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptBiayaSppActionPerformed(evt);
            }
        });
        jMenu2.add(rptBiayaSpp);

        rptDataSiswa.setText("DATA SISWA");
        rptDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptDataSiswaActionPerformed(evt);
            }
        });
        jMenu2.add(rptDataSiswa);

        mnTransaksi.setText("TRANSAKSI");
        mnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnTransaksiMouseClicked(evt);
            }
        });
        mnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksiActionPerformed(evt);
            }
        });
        jMenu2.add(mnTransaksi);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1041, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStaffMouseClicked
        // TODO add your handling code here:
        FrmStaff staff = new FrmStaff();
        dpMenuUtama.add(staff);
        staff.setVisible(true);
    }//GEN-LAST:event_menuStaffMouseClicked

    private void menuSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSiswaMouseClicked
        // TODO add your handling code here:
        FrmSiswa siswa = new FrmSiswa();
        dpMenuUtama.add(siswa);
        siswa.setVisible(true);
    }//GEN-LAST:event_menuSiswaMouseClicked

    private void menuSppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSppMouseClicked
        // TODO add your handling code here:
        FrmSpp spp = new FrmSpp();
        dpMenuUtama.add(spp);
        spp.setVisible(true);
    }//GEN-LAST:event_menuSppMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTransaksiMouseClicked
        // TODO add your handling code here:
        FrmTransaksi spp = new FrmTransaksi();
        dpMenuUtama.add(spp);
        spp.setVisible(true);
    }//GEN-LAST:event_menuTransaksiMouseClicked

    private void rptBiayaSppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptBiayaSppActionPerformed
        // TODO add your handling code here:
        try {
            Koneksi koneksiDb = new Koneksi();
            koneksiDb.getKoneksi();
            try {
                Map<String, Object> parameter = new HashMap<String, Object>();
                
                File rpt = new File("src/Report/LaporanSpp.jrxml");
                JasperDesign jasDesign = JRXmlLoader.load(rpt);
                parameter.clear();
                JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
                JasperPrint jasPrint = JasperFillManager.fillReport(jasReport, 
                        parameter, koneksiDb.getKoneksi());
                JasperViewer.viewReport(jasPrint, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Laporan tidak ditemukan" + e);
            }
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_rptBiayaSppActionPerformed

    private void rptDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptDataSiswaActionPerformed
        // TODO add your handling code here:
        try {
            Koneksi koneksiDb = new Koneksi();
            koneksiDb.getKoneksi();
            try {
                Map<String, Object> parameter = new HashMap<String, Object>();
                
                File rpt = new File("src/Report/reportSiswa.jrxml");
                JasperDesign jasDesign = JRXmlLoader.load(rpt);
                parameter.clear();
                JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
                JasperPrint jasPrint = JasperFillManager.fillReport(jasReport, 
                        parameter, koneksiDb.getKoneksi());
                JasperViewer.viewReport(jasPrint, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Laporan tidak ditemukan" + e);
            }
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_rptDataSiswaActionPerformed

    private void mnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiActionPerformed
        // TODO add your handling code here:
        try {
            Koneksi koneksiDb = new Koneksi();
            koneksiDb.getKoneksi();
            try {
                Map<String, Object> parameter = new HashMap<String, Object>();
                
                File rpt = new File("src/Report/reportTransaksi.jrxml");
                JasperDesign jasDesign = JRXmlLoader.load(rpt);
                parameter.clear();
                JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
                JasperPrint jasPrint = JasperFillManager.fillReport(jasReport, 
                        parameter, koneksiDb.getKoneksi());
                JasperViewer.viewReport(jasPrint, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Laporan tidak ditemukan" + e);
            }
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_mnTransaksiActionPerformed

    private void mnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTransaksiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dpMenuUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuSiswa;
    private javax.swing.JMenu menuSpp;
    private javax.swing.JMenu menuStaff;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JMenuItem mnTransaksi;
    private javax.swing.JMenuItem rptBiayaSpp;
    private javax.swing.JMenuItem rptDataSiswa;
    // End of variables declaration//GEN-END:variables
}
